//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankEnrollment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BankId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<System.Guid> SalesYearId { get; set; }
        public string StatusCode { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ArchiveStatusCode { get; set; }
    }
}
