//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankEnrollmentForRB
    {
        public System.Guid Id { get; set; }
        public string OfficeName { get; set; }
        public string OfficePhysicalAddress { get; set; }
        public string OfficePhysicalCity { get; set; }
        public string OfficePhysicalState { get; set; }
        public string OfficePhysicalZip { get; set; }
        public string OfficeContactFirstName { get; set; }
        public string OfficeContactLastName { get; set; }
        public string OfficeContactSSN { get; set; }
        public string OfficePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public Nullable<System.DateTime> OfficeContactDOB { get; set; }
        public string FAXNumber { get; set; }
        public string EmailAddress { get; set; }
        public string OfficeManagerFirstName { get; set; }
        public string OfficeManageLastName { get; set; }
        public string OfficeManagerSSN { get; set; }
        public Nullable<System.DateTime> OfficeManagerDOB { get; set; }
        public string OfficeManagerPhone { get; set; }
        public string OfficeManagerCellNo { get; set; }
        public string OfficeManagerEmail { get; set; }
        public string AltOfficeContact1FirstName { get; set; }
        public string AltOfficeContact1LastName { get; set; }
        public string AltOfficeContact1Email { get; set; }
        public string AltOfficeContact1SSn { get; set; }
        public string AltOfficeContact2FirstName { get; set; }
        public string AltOfficeContact2LastName { get; set; }
        public string AltOfficeContact2Email { get; set; }
        public string AltOfficeContact2SSn { get; set; }
        public string AltOfficePhysicalAddress { get; set; }
        public string AltOfficePhysicalAddress2 { get; set; }
        public string AltOfficePhysicalCity { get; set; }
        public string AltOfficePhysicalState { get; set; }
        public string AltOfficePhysicalZipcode { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingZip { get; set; }
        public string FulfillmentShippingAddress { get; set; }
        public string FulfillmentShippingCity { get; set; }
        public string FulfillmentShippingState { get; set; }
        public string FulfillmentShippingZip { get; set; }
        public string WebsiteAddress { get; set; }
        public Nullable<int> YearsinBusiness { get; set; }
        public Nullable<int> NoofBankProductsLastYear { get; set; }
        public string PreviousBankProductFacilitator { get; set; }
        public Nullable<int> ActualNoofBankProductsLastYear { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerSSN { get; set; }
        public Nullable<System.DateTime> OnwerDOB { get; set; }
        public string OwnerHomePhone { get; set; }
        public string OwnerAddress { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerZip { get; set; }
        public string LegarEntityStatus { get; set; }
        public string LLCMembershipRegistration { get; set; }
        public string BusinessName { get; set; }
        public string BusinessEIN { get; set; }
        public Nullable<System.DateTime> BusinessIncorporation { get; set; }
        public string EFINOwnerFirstName { get; set; }
        public string EFINOwnerLastName { get; set; }
        public string EFINOwnerSSN { get; set; }
        public Nullable<System.DateTime> EFINOwnerDOB { get; set; }
        public string IsMultiOffice { get; set; }
        public Nullable<int> ProductsOffering { get; set; }
        public string IsOfficeTransmit { get; set; }
        public string IsPTIN { get; set; }
        public string IsAsPerProcessLaw { get; set; }
        public string IsAsPerComplainceLaw { get; set; }
        public string ConsumerLending { get; set; }
        public Nullable<int> NoofPersoneel { get; set; }
        public string AdvertisingApproval { get; set; }
        public string EROParticipation { get; set; }
        public Nullable<decimal> SPAAmount { get; set; }
        public Nullable<System.DateTime> SPADate { get; set; }
        public string RetailPricingMethod { get; set; }
        public string IsLockedStore_Documents { get; set; }
        public string IsLockedStore_Checks { get; set; }
        public string IsLocked_Office { get; set; }
        public string IsLimitAccess { get; set; }
        public string PlantoDispose { get; set; }
        public string LoginAccesstoEmployees { get; set; }
        public string AntivirusRequired { get; set; }
        public string HasFirewall { get; set; }
        public string OnlineTraining { get; set; }
        public string PasswordRequired { get; set; }
        public Nullable<System.DateTime> EROApplicattionDate { get; set; }
        public string EROReadTAndC { get; set; }
        public string CheckingAccountName { get; set; }
        public string BankRoutingNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountType { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string StatusCode { get; set; }
        public string EFINOwnerTitle { get; set; }
        public string EFINOwnerAddress { get; set; }
        public string EFINOwnerCity { get; set; }
        public string EFINOwnerState { get; set; }
        public string EFINOwnerZip { get; set; }
        public string EFINOwnerPhone { get; set; }
        public string EFINOwnerMobile { get; set; }
        public string EFINOwnerEmail { get; set; }
        public string EFINOwnerIDNumber { get; set; }
        public string EFINOwnerIDState { get; set; }
        public string EFINOwnerEIN { get; set; }
        public string SupportOS { get; set; }
        public string BankName { get; set; }
        public string SBFeeonAll { get; set; }
        public string SBFee { get; set; }
        public string TransimissionAddon { get; set; }
        public string PrepaidCardProgram { get; set; }
        public Nullable<bool> TandC { get; set; }
        public Nullable<bool> IsEnrtyCompleted { get; set; }
        public Nullable<int> EntryLevel { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
