//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankEnrollmentForRA
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string EfinID { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerSSN { get; set; }
        public Nullable<System.DateTime> OwnerDOB { get; set; }
        public string OwnerCellPhone { get; set; }
        public string OwnerHomePhone { get; set; }
        public string OwnerAddress { get; set; }
        public string OwnerCity { get; set; }
        public string OwnerState { get; set; }
        public string OwnerZipCode { get; set; }
        public string OwnerStateIssuedIdNumber { get; set; }
        public string OwnerIssuingState { get; set; }
        public string EROOfficeName { get; set; }
        public string EROOfficeAddress { get; set; }
        public string EROOfficeCity { get; set; }
        public string EROOfficeState { get; set; }
        public string EROOfficeZipCoce { get; set; }
        public string EROOfficePhone { get; set; }
        public string EROMaillingAddress { get; set; }
        public string EROMailingCity { get; set; }
        public string EROMailingState { get; set; }
        public string EROMailingZipcode { get; set; }
        public string EROShippingAddress { get; set; }
        public string EROShippingCity { get; set; }
        public string EROShippingState { get; set; }
        public string EROShippingZip { get; set; }
        public string IRSAddress { get; set; }
        public string IRSCity { get; set; }
        public string IRSState { get; set; }
        public string IRSZipcode { get; set; }
        public Nullable<int> PreviousYearVolume { get; set; }
        public Nullable<int> ExpectedCurrentYearVolume { get; set; }
        public string PreviousBankName { get; set; }
        public string CorporationType { get; set; }
        public string CollectionofBusinessOwners { get; set; }
        public string CollectionOfOtherOwners { get; set; }
        public Nullable<int> NoofYearsExperience { get; set; }
        public string HasAssociatedWithVictims { get; set; }
        public string BusinessFederalIDNumber { get; set; }
        public string BusinessEIN { get; set; }
        public string EFINOwnersSite { get; set; }
        public string IsLastYearClient { get; set; }
        public string BankRoutingNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string StatusCode { get; set; }
        public string OwnerTitle { get; set; }
        public string SbFeeall { get; set; }
        public string TransmissionAddon { get; set; }
        public string SbFee { get; set; }
        public string ElectronicFee { get; set; }
        public Nullable<bool> AgreeTandC { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string MainContactFirstName { get; set; }
        public string MainContactLastName { get; set; }
        public string MainContactPhone { get; set; }
        public Nullable<bool> TextMessages { get; set; }
        public Nullable<bool> LegalIssues { get; set; }
        public string StateOfIncorporation { get; set; }
        public Nullable<bool> IsEnrtyCompleted { get; set; }
        public Nullable<int> EntryLevel { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
