//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankEnrollmentForTPG
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string CompanyName { get; set; }
        public string ManagerFirstName { get; set; }
        public string ManagerLastName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeCity { get; set; }
        public string OfficeState { get; set; }
        public string OfficeZip { get; set; }
        public string OfficeTelephone { get; set; }
        public string OfficeFAX { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ManagerEmail { get; set; }
        public string EFINOwnerEIN { get; set; }
        public string EFINOwnerSSN { get; set; }
        public string EFINOwnerFirstName { get; set; }
        public string EFINOwnerLastName { get; set; }
        public string EFINOwnerAddress { get; set; }
        public string EFINOwnerCity { get; set; }
        public string EFINOwnerState { get; set; }
        public string EFINOwnerZip { get; set; }
        public string EFINOwnerTelephone { get; set; }
        public Nullable<System.DateTime> EFINOwnerDOB { get; set; }
        public string EFINOwnerEmail { get; set; }
        public string BankUsedLastYear { get; set; }
        public string PriorYearEFIN { get; set; }
        public string PriorYearVolume { get; set; }
        public string PriorYearFund { get; set; }
        public string OfficeRTN { get; set; }
        public string OfficeDAN { get; set; }
        public string OfficeAccountType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string OwnerTitle { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerIdNumber { get; set; }
        public string OwnerIdState { get; set; }
        public string DocPrepFee { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string AddonFee { get; set; }
        public string ServiceBureauFee { get; set; }
        public Nullable<bool> AgreeBank { get; set; }
        public string FeeOnAll { get; set; }
        public string CheckPrint { get; set; }
        public string StatusCode { get; set; }
        public Nullable<bool> IsEnrtyCompleted { get; set; }
        public Nullable<int> EntryLevel { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    }
}
