//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankMaster()
        {
            this.BankEntityMaps = new HashSet<BankEntityMap>();
            this.BankSubQuestions = new HashSet<BankSubQuestion>();
        }
    
        public System.Guid Id { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> BankServiceFees { get; set; }
        public Nullable<decimal> MaxFeeLimitDeskTop { get; set; }
        public Nullable<decimal> MaxTranFeeDeskTop { get; set; }
        public Nullable<decimal> MaxFeeLimitMSO { get; set; }
        public Nullable<decimal> MaxTranFeeMSO { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string BankProductDocument { get; set; }
        public Nullable<System.DateTime> DeActivatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public string StatusCode { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankEntityMap> BankEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankSubQuestion> BankSubQuestions { get; set; }
    }
}
