//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uTax.EntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPersonTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactPersonTitle()
        {
            this.ContactPersonTitleCustomerMaps = new HashSet<ContactPersonTitleCustomerMap>();
        }
    
        public System.Guid Id { get; set; }
        public string ContactPersonTitle1 { get; set; }
        public System.DateTime ActivatedDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.Guid> StatusCodeId { get; set; }
    
        public virtual StatusCodeMaster StatusCodeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPersonTitleCustomerMap> ContactPersonTitleCustomerMaps { get; set; }
    }
}
