//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPersonTitleCustomerMap
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContactPersonTitleId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
    
        public virtual ContactPersonTitleMaster ContactPersonTitleMaster { get; set; }
    }
}
