//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentViaCreditCard
    {
        public System.Guid Id { get; set; }
        public System.Guid PaymentOptionId { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<int> Cardtype { get; set; }
        public string BillingAddress { get; set; }
        public string CardNumber { get; set; }
        public string Expiration { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.Guid> CreatdedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual CustomerPaymentOption CustomerPaymentOption { get; set; }
    }
}
