//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ActionMaser
    {
        public long Id { get; set; }
        public long ParentId { get; set; }
        public string Name { get; set; }
        public int ForActive { get; set; }
        public string Status { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> EntityId { get; set; }
    }
}
