//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentBankSelection
    {
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid BankId { get; set; }
        public System.Guid QuestionId { get; set; }
        public Nullable<bool> IsServiceBureauFee { get; set; }
        public Nullable<decimal> ServiceBureauBankAmount { get; set; }
        public Nullable<bool> IsTransmissionFee { get; set; }
        public Nullable<decimal> TransmissionBankAmount { get; set; }
        public Nullable<int> BankSubmissionStatus { get; set; }
        public Nullable<bool> IsPreferredBank { get; set; }
        public string StatusCode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    }
}
