//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public long ErrorId { get; set; }
        public string Query { get; set; }
        public string Parameter { get; set; }
        public string CommandType { get; set; }
        public Nullable<decimal> TotalSeconds { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
