//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeEntityMap
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FeeId { get; set; }
        public Nullable<int> EntityId { get; set; }
    
        public virtual EntityMaster EntityMaster { get; set; }
        public virtual FeeMaster FeeMaster { get; set; }
    }
}
