//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainOfficeConfiguration
    {
        public System.Guid Id { get; set; }
        public System.Guid emp_CustomerInformation_ID { get; set; }
        public bool IsSiteTransmitTaxReturns { get; set; }
        public bool IsSiteOfferBankProducts { get; set; }
        public int TaxProfessionals { get; set; }
        public bool IsSoftwarebeInstalledNetwork { get; set; }
        public int ComputerswillruninSoftware { get; set; }
        public int PreferredSupportLanguage { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public string StatusCode { get; set; }
        public bool HasBusinessSoftware { get; set; }
        public bool IsSharingEfin { get; set; }
    }
}
