//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Onboarding
    {
        public System.Guid RowId { get; set; }
        public string CaseId { get; set; }
        public int AdminStatus { get; set; }
        public int InstallCurrentYearStatus { get; set; }
        public int BankEnrollmentStatus { get; set; }
        public int ConversionStatus { get; set; }
        public int DbConfigurationStatus { get; set; }
        public int InstallNewYearStatus { get; set; }
        public int MobileAppStatus { get; set; }
        public string AdminLastEditedById { get; set; }
        public string InstallCurrentYearLastEditedById { get; set; }
        public string BankEnrollmentLastEditedById { get; set; }
        public string ConversionLastEditedById { get; set; }
        public string DbConfigurationLastEditedById { get; set; }
        public string InstallNewYearLastEditedById { get; set; }
        public string MobileAppLastEditedById { get; set; }
        public Nullable<System.DateTime> AdminLastModifiedDate { get; set; }
        public Nullable<System.DateTime> InstallCurrentYearLastModifiedDate { get; set; }
        public Nullable<System.DateTime> BankEnrollmentLastModifiedDate { get; set; }
        public Nullable<System.DateTime> ConversionLastModifiedDate { get; set; }
        public Nullable<System.DateTime> DbConfigurationLastModifiedDate { get; set; }
        public Nullable<System.DateTime> InstallNewYearLastModifiedDate { get; set; }
        public Nullable<System.DateTime> MobileAppLastModifiedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedById { get; set; }
    }
}
