//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermissionMap
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public Nullable<System.Guid> PermissionId { get; set; }
    
        public virtual PermissionMaster PermissionMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
