//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesforce_Account
    {
        public long SFDC_AccountSyncID { get; set; }
        public string AccountID { get; set; }
        public string Master_Identifier__c { get; set; }
        public string EFIN__c { get; set; }
        public string Transmission_Password__c { get; set; }
        public string ParentID { get; set; }
        public string Feeder_Sites__c { get; set; }
        public string Name { get; set; }
        public string ERO_Type__c { get; set; }
        public string BillingStreet { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string ShippingStreet { get; set; }
        public string ShippingCIty { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string MSO_User__c { get; set; }
        public string Co_Branding__c { get; set; }
        public string TPG_Check_Print_Software__c { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string User_ID__c { get; set; }
        public string EFIN_Status__c { get; set; }
    }
}
