//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesforce_Opportunity
    {
        public long SFDC_OpportunitySyncID { get; set; }
        public string OpportunityID { get; set; }
        public string AccountID { get; set; }
        public string OpportunityOwnerID { get; set; }
        public string AccountOwnerID { get; set; }
        public string Tax_Season__c { get; set; }
        public string Quote_Software_Package__c { get; set; }
        public string uTax_Not_Collecting_SB_Fees__c { get; set; }
        public Nullable<decimal> Transmitter_Fee__c { get; set; }
        public Nullable<decimal> Technology_Fee__c { get; set; }
        public Nullable<decimal> Quote_Bank_Product_uTax_Fee__c { get; set; }
        public Nullable<decimal> Quote_Federal_EF_Fee__c { get; set; }
        public Nullable<decimal> Quote_State_EF_Fee__c { get; set; }
        public string OpportunityType { get; set; }
        public string StageName { get; set; }
        public Nullable<System.DateTime> OpportunityLastModifiedDate { get; set; }
        public Nullable<System.DateTime> OpportunityLastActivityDate { get; set; }
        public Nullable<bool> IsEMPCustomerCreated { get; set; }
        public string EMPCustomerID { get; set; }
        public Nullable<System.DateTime> EmpCustomerCreatedDtTm { get; set; }
        public string User_ID__c { get; set; }
        public Nullable<decimal> A_R_Amount_Due_Credit__c { get; set; }
        public string Cash_Saver__c { get; set; }
        public Nullable<decimal> pymt__Balance__c { get; set; }
        public string LOC_Program_Participant__c { get; set; }
        public Nullable<decimal> Total_Amount_Loaned__c { get; set; }
        public Nullable<decimal> Federal_EF_Fee_New__c { get; set; }
        public Nullable<decimal> State_EF_Fee_New__c { get; set; }
    }
}
