//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesforce_Contact
    {
        public long SFDC_ContactSyncID { get; set; }
        public string ContactID { get; set; }
        public string AccountID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Primary_Contact__c { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
