//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitemapEntity
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SitemapId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> DisplayPartial { get; set; }
        public string DisplayClass { get; set; }
    }
}
