//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCode
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string DisplayText { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string RefType { get; set; }
        public Nullable<int> RefTypeId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
