//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uTax.EntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCodeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusCodeMaster()
        {
            this.AccessTypeMasters = new HashSet<AccessTypeMaster>();
            this.AffiliationProgramEntityMaps = new HashSet<AffiliationProgramEntityMap>();
            this.APIIntegrations = new HashSet<APIIntegration>();
            this.BankEntityMaps = new HashSet<BankEntityMap>();
            this.BankMasters = new HashSet<BankMaster>();
            this.BankSubQuestions = new HashSet<BankSubQuestion>();
            this.ContactPersonTitles = new HashSet<ContactPersonTitle>();
            this.ContactPersonTitleCustomerMaps = new HashSet<ContactPersonTitleCustomerMap>();
            this.CustomerMasters = new HashSet<CustomerMaster>();
            this.EntityMasters = new HashSet<EntityMaster>();
            this.FeeEntityMaps = new HashSet<FeeEntityMap>();
            this.FeeMasters = new HashSet<FeeMaster>();
            this.GroupMasters = new HashSet<GroupMaster>();
            this.GroupRoleMaps = new HashSet<GroupRoleMap>();
            this.NotificationMasters = new HashSet<NotificationMaster>();
            this.PermissionMasters = new HashSet<PermissionMaster>();
            this.PhoneTypeCustomerMaps = new HashSet<PhoneTypeCustomerMap>();
            this.PhoneTypeMasters = new HashSet<PhoneTypeMaster>();
            this.RoleMasters = new HashSet<RoleMaster>();
            this.SalesYearEntityMaps = new HashSet<SalesYearEntityMap>();
            this.SalesYearMasters = new HashSet<SalesYearMaster>();
            this.SecurityAnswerUserMaps = new HashSet<SecurityAnswerUserMap>();
            this.SecurityQuestionMasters = new HashSet<SecurityQuestionMaster>();
            this.SitemapMasters = new HashSet<SitemapMaster>();
            this.SitemapRoleMaps = new HashSet<SitemapRoleMap>();
            this.TooltipMasters = new HashSet<TooltipMaster>();
            this.UserMasters = new HashSet<UserMaster>();
            this.UserNotificationsMaps = new HashSet<UserNotificationsMap>();
            this.UserRolesMaps = new HashSet<UserRolesMap>();
        }
    
        public System.Guid Id { get; set; }
        public string StatusCodes { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.Guid> StatusCodeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessTypeMaster> AccessTypeMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliationProgramEntityMap> AffiliationProgramEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APIIntegration> APIIntegrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankEntityMap> BankEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankMaster> BankMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankSubQuestion> BankSubQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPersonTitle> ContactPersonTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPersonTitleCustomerMap> ContactPersonTitleCustomerMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMaster> CustomerMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityMaster> EntityMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeEntityMap> FeeEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeMaster> FeeMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMaster> GroupMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRoleMap> GroupRoleMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationMaster> NotificationMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionMaster> PermissionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneTypeCustomerMap> PhoneTypeCustomerMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneTypeMaster> PhoneTypeMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMaster> RoleMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesYearEntityMap> SalesYearEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesYearMaster> SalesYearMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityAnswerUserMap> SecurityAnswerUserMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityQuestionMaster> SecurityQuestionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitemapMaster> SitemapMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitemapRoleMap> SitemapRoleMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TooltipMaster> TooltipMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMaster> UserMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotificationsMap> UserNotificationsMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRolesMap> UserRolesMaps { get; set; }
    }
}
