//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSiteOfficeConfig
    {
        public System.Guid Id { get; set; }
        public System.Guid RefId { get; set; }
        public bool EFINListedOtherOffice { get; set; }
        public bool SiteOwnthisEFIN { get; set; }
        public string EFINOwnerSite { get; set; }
        public int SOorSSorEFIN { get; set; }
        public bool SubSiteSendTaxReturn { get; set; }
        public bool SiteanMSOLocation { get; set; }
        public Nullable<bool> IsMainSiteTransmitTaxReturn { get; set; }
        public Nullable<int> NoofTaxProfessionals { get; set; }
        public Nullable<bool> IsSoftwareOnNetwork { get; set; }
        public Nullable<int> NoofComputers { get; set; }
        public Nullable<int> PreferredLanguage { get; set; }
        public Nullable<bool> CanSubSiteLoginToEmp { get; set; }
        public string StatusCode { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public bool HasBusinessSoftware { get; set; }
        public bool IsSharingEFIN { get; set; }
    }
}
