//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSiteConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSiteConfiguration()
        {
            this.SubSiteAffiliateProgramConfigs = new HashSet<SubSiteAffiliateProgramConfig>();
            this.SubSiteBankConfigs = new HashSet<SubSiteBankConfig>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid emp_CustomerInformation_ID { get; set; }
        public Nullable<bool> IsuTaxManageingEnrolling { get; set; }
        public Nullable<bool> IsuTaxPortalEnrollment { get; set; }
        public Nullable<bool> IsuTaxManageOnboarding { get; set; }
        public Nullable<bool> IsuTaxCustomerSupport { get; set; }
        public bool CanSubSiteLoginToEmp { get; set; }
        public Nullable<int> NoofSupportStaff { get; set; }
        public string NoofDays { get; set; }
        public Nullable<System.TimeSpan> OpenHours { get; set; }
        public Nullable<System.TimeSpan> CloseHours { get; set; }
        public string TimeZone { get; set; }
        public Nullable<bool> IsAutoEnrollAffiliateProgram { get; set; }
        public Nullable<int> SubSiteTaxReturn { get; set; }
        public Nullable<bool> IsSubSiteEFINAllow { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public string StatusCode { get; set; }
        public Nullable<bool> EnrollmentEmails { get; set; }
    
        public virtual emp_CustomerInformation emp_CustomerInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSiteAffiliateProgramConfig> SubSiteAffiliateProgramConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSiteBankConfig> SubSiteBankConfigs { get; set; }
    }
}
