//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCase
    {
        public string AccountSfdcId { get; set; }
        public System.Guid Id { get; set; }
        public string AssignedAgentId { get; set; }
        public Nullable<bool> BankEnrollment { get; set; }
        public string CctSelections { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string CreatedByAgentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public string FunctionalArea { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDeleted { get; set; }
        public string Issue { get; set; }
        public string LastModifiedByAgentId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime LastViewedDate { get; set; }
        public string LockedByAgentId { get; set; }
        public string Module { get; set; }
        public string Origin { get; set; }
        public string Priority { get; set; }
        public string Product { get; set; }
        public string Reason { get; set; }
        public string SfdcCaseNumber { get; set; }
        public string Status { get; set; }
        public string Subject { get; set; }
        public string TaxSeason { get; set; }
        public string Type { get; set; }
    }
}
