//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPEntityFramework.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TooltipMaster
    {
        public System.Guid Id { get; set; }
        public string Field { get; set; }
        public string ToolTipText { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> SitemapId { get; set; }
        public Nullable<bool> IsUIVisible { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public string StatusCode { get; set; }
    
        public virtual SitemapMaster SitemapMaster { get; set; }
    }
}
